### ISSUE TITLE
Cool plugin

### ISSUE THREAD

**Issue by Raskoll2** [elijah-potter/harper-obsidian-plugin#1]
Does this only work this words obsidian recognizes as wrong? I think Obsidian's built in thing mostly just works for spelling. Also how did yo pick that name lol. Cool overall, I like the UI

**Comment by elijah-potter** [comment]
Harper does spellchecking in other contexts, but it's disabled (since it is built in) in Obsidian.
It does higher-level grammar analysis by parsing English language and running a series of linters over it. If you are still curious, check out the [source](https://github.com/elijah-potter/harper/tree/master/harper-core)
